name: Run Python Script

on:
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install ImageMagick
      run: sudo apt-get install -y imagemagick

    - name: Run Python script
      run: |
        echo "Current working directory: $(pwd)"
        mkdir -p Preview
        python Python/generate_and_solve.py

    - name: Configure Git
      run: |
        git config --global user.name 'pakelcomedy'
        git config --global user.email 'danieldna1411@gmail.com'

    - name: Commit and push changes
      run: |
        git add README.md
        git commit -m 'Update Algorithm' || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/pakelcomedy/Sorting-Puzzle-Generator.git HEAD:main
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Verify files
      run: |
        echo "Contents of Preview directory:"
        ls -l Preview
        echo "Contents of repository root:"
        ls -l

    - name: Upload animation and README
      uses: actions/upload-artifact@v3
      with:
        name: results
        path: |
          Preview/merge_sort_animation.gif
          README.md
