name: Run Python Script

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install ImageMagick
      run: sudo apt-get install -y imagemagick

    - name: Run Python script
      run: |
        echo "Current working directory: $(pwd)"
        mkdir -p Preview
        python Python/generate_and_solve.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add README.md
        git commit -m 'Update README.md with new content'
        git push

    - name: Verify files
      run: |
        echo "Contents of Preview directory:"
        ls -l Preview
        echo "Contents of repository root:"
        ls -l

    - name: Upload animation and README
      uses: actions/upload-artifact@v3
      with:
        name: results
        path: |
          Preview/merge_sort_animation.gif
          README.md
