name: Run Python Script Every Hour

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour at minute 0
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Python version used in the workflow

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Install dependencies if any

    - name: Install ImageMagick
      run: sudo apt-get update && sudo apt-get install -y imagemagick

    - name: Run Python script
      run: |
        python python/generate_and_solve.py  # Run the Python script from the root directory

    - name: Commit changes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "your-email@example.com"
        git add .
        git commit -m "Update generated files and animation" || echo "No changes to commit"
        git push origin main
